steps:
- id: build-app
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/swagger:1.0.0', './swagger']
- id: push-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/swagger:1.0.0']
- id: deploy
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'swagger'
  - '--image'
  - 'gcr.io/$PROJECT_ID/swagger:1.0.0'
  - '--allow-unauthenticated'
  - '--project'
  - '$_PROJECT'
  - '--region'
  - '$_REGION'
